### ISSUE TITLE
Prepare for v1.0 release

### ISSUE THREAD

**Issue by slosar** [lusee-night/luseepy#27]
We need the following items to be fixed by before v1 (tick off you do work and comment below):

 - [ ]  We need start versioning docker images. now we have two images
called  `lusee/lusee-night-jupyter:0.1` but in the latest the jupyter notebook is deprecated (for jupyter hub)  and so
`setup_env.sh` does not work any more. I suggest we bump the version to 0.2 and then every time we do anything
we update the minor version .201, .202, etc The latest version of docker should also come with the latest version of luseepy.

- [x] We need a version in luseepy. I want lusee.__version__ to be some sensible string. I suggest we use dates rather than version numbers, so Sep22 would be good.

- [x]  We need a general luseepy code cleanup. This involves making sure uniform capitalization convention is used across. Perhaps rename all the LBeam, LSatellite etc objects into simply Beam, Satellite etc as all live under lusee module. Make sure the same spacing etc convnetions are used. Perhaps just run black on evertyhing or something.

 - [x]  we need stub documentation and a page at the readthedocs.org

 - [ ] We need to make luseepy be pip installable package as many people still rely on conda environments etc for docker images.

**Comment by buddhasystem** [comment]
Do we want a LuSEE account on "readthedocs"? It would seem so. Please advise.

**Comment by buddhasystem** [comment]
Added lusee version to the branch, for now '20220831'

**Comment by slosar** [comment]
> 

I think so. I don't know, I've never set up any of this directly. I would like something that is self-documenting as in pull documentation from doc strings.
You should set up and put doc strings stubs everywhere they are needed, including variable names -- i can then fill in the details.

**Comment by buddhasystem** [comment]
OK, so one option to integrate with "READTHEDOCS" is to use the GitHub account. So the authorization for "readthedocs" to access a particular repo is given by one of the owners, which makes sense. I've set up a sandbox for initial experimentation, will extend to my luseepy branch.

**Comment by buddhasystem** [comment]
Boilerplate for RTD has been added to my branch. I don't know the details of the code so adding docstrings will probably a task for developers.

NB. RTD operates with the requirements that all dependencies are satisfied. At the same time, they disallow users' containers. This means that packages need to be specified in the requirements file accessed by RTD. This leads to a longer build time, but what do you do...

**Comment by buddhasystem** [comment]
Started on capitalization, work in progress

**Comment by buddhasystem** [comment]
Chose the camelback notation, underscores just make folders less readable

**Comment by slosar** [comment]
Are we ready to close this?
